// <auto-generated/>
#nullable enable

namespace TestApp;

/// <summary>
/// 为当前分部类型补充自动生成的优先级契约实现。
/// </summary>
partial class MySystem : global::GFramework.Core.Abstractions.Bases.IPrioritized
{
    /// <summary>
    /// 获取优先级值: 10
    /// </summary>
    public int Priority => 10;
}
