// <auto-generated />
using GFramework.Core.Abstractions.Logging;
using GFramework.Core.Logging;

namespace TestApp;

/// <summary>
/// 为当前分部类型提供自动生成的日志字段。
/// </summary>
partial class MyService
{
    /// <summary>
    /// 自动生成的日志字段。
    /// </summary>
    private readonly ILogger _log = LoggerFactoryResolver.Provider.CreateLogger("MyService");
}
